apps/Astrolabe/API_festivals/urls.py
from django.urls import path, include
from .views import *
from .viewsets import *
from rest_framework import routers

app_name = 'API_festivals'

routers = routers.SimpleRouter()
routers.register('artistes', ArtisteViewSet, basename='artistes')
routers.register('performances', PerformanceViewSet, basename='performances')
routers.register('scenes', SceneViewSet, basename='scenes')
routers.register('configuration', ConfigurationFestivalViewSet, basename='configuration')
routers.register('partenaires', PartenaireViewSet, basename='partenaires')
routers.register('modifications', ModificationViewSet, basename='modifications')
routers.register('news',NewsViewSet,basename="news")
routers.register('tags', TagsViewSet, basename="tags")

urlpatterns = [
    path('v0/', include(routers.urls)),
    path('', accueil, name='accueil'),
    path('configuration/', configuration, name='configuration'),
    path('configuration/update', configuration_update, name='configuration_update'),
    path('configuration/delete', configuration_delete, name='configuration_delete'),
    path('artistes/<int:page>', artistes, name='artistes'),
    path('artistes/detail/<int:id>', artiste_detail, name='artiste_detail'),
    path('artistes/update/<int:id>', artiste_update, name='artiste_update'),
    path('artistes/delete/<int:id>', artiste_delete, name='artiste_delete'),
    path('artistes/create', artiste_create, name='artiste_create'),
    path('partenaires/<int:page>', partenaires, name='partenaires'),
    path('partenaires/detail/<int:id>', partenaire_detail, name='partenaire_detail'),
    path('partenaires/update/<int:id>', partenaire_update, name='partenaire_update'),
    path('partenaires/delete/<int:id>', partenaire_delete, name='partenaire_delete'),
    path('partenaires/create', partenaire_create, name='partenaire_create'),
    path('performances/<int:page>', performances, name='performances'),
    path('performances/detail/<int:id>', performance_detail, name='performance_detail'),
    path('performances/update/<int:id>', performance_update, name='performance_update'),
    path('performances/delete/<int:id>', performance_delete, name='performance_delete'),
    path('performances/create', performance_create, name='performance_create'),
    path('scenes/<int:page>', scenes, name='scenes'),
    path('scenes/detail/<int:id>', scene_detail, name='scene_detail'),
    path('scenes/update/<int:id>', scene_update, name='scene_update'),
    path('scenes/delete/<int:id>', scene_delete, name='scene_delete'),
    path('scenes/create', scene_create, name='scene_create'),
    path('news/<int:page>', news, name='news'),
    path('news/detail/<int:id>', news_detail, name='news_detail'),
    path('news/update/<int:id>', news_update, name='news_update'),
    path('news/delete/<int:id>', news_delete, name='news_delete'),
    path('news/create', news_create, name='news_create'),
    path('tags/', tags, name='tags'),
    path('tags/detail/<int:id>', tag_detail, name='tag_detail'),
    path('tags/update/<int:id>', tag_update, name='tag_update'),
    path('tags/delete/<int:id>', tag_delete, name='tag_delete'),
    path('tags/create', tag_create, name='tag_create'),
    path('parametres/',parametres, name='parametres'),
]

apps/Astrolabe/Astrolabe/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/',include('rest_framework.urls')),
    path('festivals/', include('API_festivals.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

handler404 = 'API_festivals.views.not_found'

apps/Astrolabe/API_festivals/views.py
import json
from .serializers import *
from .views_tools import *
from .models import *
from .forms import *
from django.shortcuts import redirect, render, get_object_or_404
import os
from datetime import date
from django.utils import timezone

# --------------------------------------------------------------- DECORATEURS ---------------------------------------------------------------------
def configuration_required(view_func):
    def wrapped_view(request, *args, **kwargs):
        if request.method == "GET":
            configuration = ConfigurationFestival.objects.all()
            if configuration.exists():
                return view_func(request, *args, **kwargs)
            else:
                return redirect('API_festivals:configuration')

        # Si la méthode HTTP n'est pas GET, laissez la vue originale gérer la requête.
        return view_func(request, *args, **kwargs)

    return wrapped_view

# --------------------------------------------------------------- CONTROLLEURS ---------------------------------------------------------------------

@configuration_required
def accueil(request):
    festival = ConfigurationFestival.objects.all().first()
    performances_par_jour = dict()
    performances_jour = Performance.objects.filter(date__gte=timezone.now()).order_by('date', 'heure_debut')
    tag_form = TagsFilterForm(request.GET)
    
    if 'tags' in request.GET:
        tag_id = request.GET.getlist('tags')[0]
        if tag_id != '-1' :
            tag = Tag.objects.get(pk=tag_id)
            performances_jour = tag.performances.filter(date__gte=timezone.now()).order_by('date')
        

    for perf in performances_jour:
        artistes = Artiste.objects.filter(performance=perf)
        if perf.date not in performances_par_jour.keys():
            performances_par_jour[perf.date] = [(perf,artistes)]
        else :
            performances_par_jour[perf.date].append((perf,artistes))
    news_par_jours = dict()
    news_jour = News.objects.filter(date__gte=timezone.now()).order_by('date')
    for news in news_jour:
        if news.date not in news_par_jours.keys():
            news_par_jours[news.date] = [news]
        else :
            news_par_jours[news.date].append(news)
    return render(request, 'accueil.html', {'tag_form':tag_form,'tag_data': Tag.objects.filter(visible=True),'nom_festival':festival.nom,'performances_par_jour':performances_par_jour,'logo':festival.logo, 'news_par_jours':news_par_jours})

# CONFIGURATION
def configuration(request):
    """
    Renvoyer la création s'il n'y a pas de configuration d'enregistrée dans la base de données
    Renvoyer la page de détail sinon.
    """
    form = ConfigurationFestivalForm()
    partenaire_form = PartenaireForm()
    artiste_form = ArtisteForm()
    if request.method == "GET":
        configuration = ConfigurationFestival.objects.all()
        if configuration.exists():
            config_instance = configuration.first()
            partenaires = Partenaire.objects.filter(id__in=config_instance.partenaires.all()).all()
            return render(request,'configuration/configuration_detail.html',{'configuration':config_instance,'partenaires':partenaires})
        return render(request,'configuration/configuration_create.html',{'form':form,'partenaire_form':partenaire_form,"artiste_form":artiste_form,})
    elif request.method == "POST":
        form = ConfigurationFestivalForm(request.POST, request.FILES)
        if form.is_valid():
            Tag.objects.all().delete()
            generer_tags_date_festival(form.cleaned_data['date_debut'],form.cleaned_data['date_fin'])
            form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_config = timezone.now()
            modif.save()
            return redirect('API_festivals:configuration')
    return render(request,'configuration/configuration_create.html',{'form':form,'partenaire_form':partenaire_form,"artiste_form":artiste_form})

@configuration_required
def configuration_update(request):
    configuration = ConfigurationFestival.objects.all().first()
    chemin_logo = str(configuration.logo)
    configuration_form = ConfigurationFestivalForm(instance=configuration)
    if request.method == 'POST':
        configuration_form = ConfigurationFestivalForm(request.POST, request.FILES, instance=configuration)
        if configuration_form.has_changed() and configuration_form.is_valid():
            if "logo" in configuration_form.changed_data:
                try :
                    os.remove(chemin_logo)
                except FileNotFoundError :
                    pass
            configuration_form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_config = timezone.now()
            modif.save()
            return redirect('API_festivals:configuration')
    partenaire_form =PartenaireForm()
    artiste_form = ArtisteForm()
    return render(request, 'configuration/configuration_update.html', {'form': configuration_form, 'partenaire_form':partenaire_form, "artiste_form":artiste_form,'configuration': configuration})

@configuration_required
def configuration_delete(request):
    configuration = ConfigurationFestival.objects.all().first()
    try:
        os.remove(str(configuration.logo))
        os.remove(str(configuration.video_promo))
    except FileNotFoundError:
        pass
    if get_parameters("Delete_all_on_configuration_delete") == True:
        export_data()
        delete_all_data()
    configuration.delete()
    modif = Modification.objects.all().first()
    modif.date_modif_config = timezone.now()
    modif.save()
    return redirect("API_festivals:configuration")

# ARTISTES
@configuration_required
def artistes(request,page):
    artistes = Artiste.objects.all()
    logo = ConfigurationFestival.objects.all().first().logo
    form = SearchForm(request.GET)
    if form.is_valid():
        search_term = form.cleaned_data['search']
        artistes = artistes.filter(nom__icontains=search_term)
    render_left_arrow,render_right_arrow,artistes = pagination(artistes,page,Artiste.objects.all())
    return render(request, 'artistes/artistes.html',{"logo":logo,"artistes": artistes,"form":form,
     "render_right_arrow":render_right_arrow,"render_left_arrow":render_left_arrow, "page_precedente": page-1, "page_suivante": page+1})

@configuration_required
def artiste_create(request):
    modal = request.GET.get('modal',False)
    logo = ConfigurationFestival.objects.all().first().logo
    referer = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        artiste_form = ArtisteForm(request.POST, request.FILES)
        if artiste_form.is_valid():
            artiste_form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_artiste = timezone.now()
            modif.save()
            if not modal : 
                return redirect('API_festivals:artistes', page=1)
            elif 'configuration' in referer:
                if 'update' in referer:
                    return redirect('API_festivals:configuration_update')
                elif 'create' in referer :
                    return redirect('API_festivals:configuration')
            else : 
                if 'update' in referer:
                    return redirect('API_festivals:performance_update')
                elif 'create' in referer :
                    return redirect('API_festivals:performance_create')
    else:
        artiste_form = ArtisteForm()
    return render(request, 'artistes/artiste_create.html', {'form': artiste_form,'logo':logo})

@configuration_required
def artiste_detail(request, id):
    perf_exist = False
    logo = ConfigurationFestival.objects.all().first().logo
    artiste = get_object_or_404(Artiste,id=id)
    perfs = Performance.objects.filter(artistes=artiste)
    if perfs.exists():
        perf_exist = True
    artistes = artiste.recommendations.all()
    template = "artistes/artiste_detail.html"
    context = {'artiste': artiste,'logo':logo,'artistes':artistes,'perf_exist':perf_exist}
    return render(request, template, context)

@configuration_required
def artiste_update(request, id):
    if Artiste.objects.all().exists():
        logo = ConfigurationFestival.objects.all().first().logo
        artiste = get_object_or_404(Artiste,id=id)
        chemin_image = str(artiste.image)
        artiste_form = ArtisteForm(instance=artiste)
        if request.method == 'POST':
            artiste_form = ArtisteForm(request.POST, request.FILES, instance=artiste)
            if artiste_form.has_changed() and artiste_form.is_valid():
                try : 
                    if "image" in artiste_form.changed_data:
                        os.remove(chemin_image)
                except FileNotFoundError :
                    pass
                finally :
                    artiste_form.save()
                    modif = Modification.objects.all().first()
                    modif.date_modif_artiste = timezone.now()
                    modif.save()
                    return redirect('API_festivals:artiste_detail', id=id)
        return render(request, 'artistes/artiste_update.html', {'logo':logo,'form': artiste_form, 'artiste': artiste})
    else :
        return redirect('API_festivals:artiste_create')

@configuration_required
def artiste_delete(request, id):
    artiste = get_object_or_404(Artiste,id=id)
    confirmation = request.GET.get('confirmation',False)
    perfs = Performance.objects.filter(artistes=artiste)
    if confirmation:
        for perf in perfs:
            perf.delete()
    try :
        os.remove(str(artiste.image.path)) 
    except FileNotFoundError:
        pass
    finally:
        artiste.delete()
    # Update modification date
    modif = Modification.objects.first()
    modif.date_modif_artiste = timezone.now()
    modif.save()
    return redirect("API_festivals:artistes", page=1)

# PARTENAIRES
@configuration_required

apps/Astrolabe/API_festivals/templates/scenes/scene_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}Nouvelle scène{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<div class="container" style="text-align: center;">
    <h2>Création d'une nouvelle scène</h2>
</div>
<form class="persoForm" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% with WIDGET_ERROR_CLASS='champsInvalide' WIDGET_REQUIRED_CLASS='champsRequis'%}
        {% for field in form %}
            {{ field.label_tag }}
            {% render_field field %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <p style="color: red;">* {{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endwith %}
    <input type="submit" value="Enregistrer">
</form>
{% endblock %}

apps/Astrolabe/API_festivals/templates/scenes/scene_detail.html
{% extends 'base.html' %}
{% block title %}{{scene.nom}}{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<table class="table table-bordered shadow-lg table-rounded">
    <thead>
        <tr>
            <th scope="col" style="width: 20%;">Paramètre</th>
            <th scope="col" style="width: 80%;">Valeur</th>
        </tr>
    </thead>
    <tbody>
        <tr class="table-light">
            <th scope="row">Nom</th>
            <td>{{ scene.nom }}</td>
        </tr>
        <tr class="table-light">
            <th scope="row">Image</th>
            <td><img src="/{{scene.image}}" alt="{{scene.nom}}"></td>
        </tr>
        <tr class="table-light">
            <th scope="row">Lieu</th>
            <td>{{scene.lieu}}</td>
        </tr>
        <tr class="table-light">
            <th scope="row">Performance(s)</th>
            <td>
                {% for performance in performances %}
                <a href="{% url 'API_festivals:performance_detail' performance.id %}">{{performance.nom}}</a>
                {% endfor %}
            </td>
        </tr>
    </tbody>
</table>
<a href="{% url 'API_festivals:scene_update' id=scene.id %}" class="btn btn-warning">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
    </svg>
    Modifier
</a>
<a class="btn btn-danger"  data-bs-toggle="modal" data-bs-target="#myModal">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
    </svg>
    Supprimer
</a>
{% include '../modal/scenes/scene_delete.html' %}
{% endblock %}

apps/Astrolabe/API_festivals/templates/scenes/scene_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}{{scene.nom}}{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<div class="container" style="text-align: center;">
    <h2>Modification de {{scene.nom}}</h2>
</div>
<form class="persoForm" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% with WIDGET_ERROR_CLASS='champsInvalide' WIDGET_REQUIRED_CLASS='champsRequis'%}
        {% for field in form %}
            {{ field.label_tag }}
            {% render_field field %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <p style="color: red;">* {{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endwith %}
    <input type="submit" value="Enregistrer">
</form>
{% endblock %}

apps/Astrolabe/API_festivals/templates/scenes/scenes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Scènes{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<form method="GET">
    {% csrf_token %}
    {{ form.search|as_crispy_field }}
</form>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for scene in scenes %}
    <div class="col">
        <a class="nolink" href="{% url 'API_festivals:scene_detail' scene.id %}">
            <div class="card mb-3 entity" style="max-width: 540px; margin-bottom: 1em;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img class="rounded-start-5 rounded-end-0" src="/{{scene.image}}" alt="{{image.nom}}" style="object-fit: cover; width: 100%; height: 150px;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h3 class="card-title" >{{ scene.nom }}</h3>
                            <p class="card-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/>
                                </svg>
                                {{scene.lieu}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
<div>
    {% if render_left_arrow %}
    <a href="{% url 'API_festivals:scenes' page=page_precedente %}" class="btn btn-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
        </svg>
    </a>
    {% else %}
    <button class="btn btn-secondary" disabled>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
        </svg>
    </button>
    {% endif %}
    {% if render_right_arrow %}
    <a href="{% url 'API_festivals:scenes' page=page_suivante %}" class="btn btn-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
        </svg>
    </a>
    {% else %}
    <button class="btn btn-secondary" disabled>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8"/>
        </svg>
    </button>
    {% endif %}
</div>
{% endblock %}