apps/Astrolabe/API_festivals/urls.py
from django.urls import path, include
from .views import *
from .viewsets import *
from rest_framework import routers

app_name = 'API_festivals'

routers = routers.SimpleRouter()
routers.register('artistes', ArtisteViewSet, basename='artistes')
routers.register('performances', PerformanceViewSet, basename='performances')
routers.register('scenes', SceneViewSet, basename='scenes')
routers.register('configuration', ConfigurationFestivalViewSet, basename='configuration')
routers.register('partenaires', PartenaireViewSet, basename='partenaires')
routers.register('modifications', ModificationViewSet, basename='modifications')
routers.register('news',NewsViewSet,basename="news")
routers.register('tags', TagsViewSet, basename="tags")

urlpatterns = [
    path('v0/', include(routers.urls)),
    path('', accueil, name='accueil'),
    path('configuration/', configuration, name='configuration'),
    path('configuration/update', configuration_update, name='configuration_update'),
    path('configuration/delete', configuration_delete, name='configuration_delete'),
    path('artistes/<int:page>', artistes, name='artistes'),
    path('artistes/detail/<int:id>', artiste_detail, name='artiste_detail'),
    path('artistes/update/<int:id>', artiste_update, name='artiste_update'),
    path('artistes/delete/<int:id>', artiste_delete, name='artiste_delete'),
    path('artistes/create', artiste_create, name='artiste_create'),
    path('partenaires/<int:page>', partenaires, name='partenaires'),
    path('partenaires/detail/<int:id>', partenaire_detail, name='partenaire_detail'),
    path('partenaires/update/<int:id>', partenaire_update, name='partenaire_update'),
    path('partenaires/delete/<int:id>', partenaire_delete, name='partenaire_delete'),
    path('partenaires/create', partenaire_create, name='partenaire_create'),
    path('performances/<int:page>', performances, name='performances'),
    path('performances/detail/<int:id>', performance_detail, name='performance_detail'),
    path('performances/update/<int:id>', performance_update, name='performance_update'),
    path('performances/delete/<int:id>', performance_delete, name='performance_delete'),
    path('performances/create', performance_create, name='performance_create'),
    path('scenes/<int:page>', scenes, name='scenes'),
    path('scenes/detail/<int:id>', scene_detail, name='scene_detail'),
    path('scenes/update/<int:id>', scene_update, name='scene_update'),
    path('scenes/delete/<int:id>', scene_delete, name='scene_delete'),
    path('scenes/create', scene_create, name='scene_create'),
    path('news/<int:page>', news, name='news'),
    path('news/detail/<int:id>', news_detail, name='news_detail'),
    path('news/update/<int:id>', news_update, name='news_update'),
    path('news/delete/<int:id>', news_delete, name='news_delete'),
    path('news/create', news_create, name='news_create'),
    path('tags/', tags, name='tags'),
    path('tags/detail/<int:id>', tag_detail, name='tag_detail'),
    path('tags/update/<int:id>', tag_update, name='tag_update'),
    path('tags/delete/<int:id>', tag_delete, name='tag_delete'),
    path('tags/create', tag_create, name='tag_create'),
    path('parametres/',parametres, name='parametres'),
]

apps/Astrolabe/Astrolabe/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/',include('rest_framework.urls')),
    path('festivals/', include('API_festivals.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

handler404 = 'API_festivals.views.not_found'

apps/Astrolabe/API_festivals/views.py
import json
from .serializers import *
from .views_tools import *
from .models import *
from .forms import *
from django.shortcuts import redirect, render, get_object_or_404
import os
from datetime import date
from django.utils import timezone

# --------------------------------------------------------------- DECORATEURS ---------------------------------------------------------------------
def configuration_required(view_func):
    def wrapped_view(request, *args, **kwargs):
        if request.method == "GET":
            configuration = ConfigurationFestival.objects.all()
            if configuration.exists():
                return view_func(request, *args, **kwargs)
            else:
                return redirect('API_festivals:configuration')

        # Si la méthode HTTP n'est pas GET, laissez la vue originale gérer la requête.
        return view_func(request, *args, **kwargs)

    return wrapped_view

# --------------------------------------------------------------- CONTROLLEURS ---------------------------------------------------------------------

@configuration_required
def accueil(request):
    festival = ConfigurationFestival.objects.all().first()
    performances_par_jour = dict()
    performances_jour = Performance.objects.filter(date__gte=timezone.now()).order_by('date', 'heure_debut')
    tag_form = TagsFilterForm(request.GET)
    
    if 'tags' in request.GET:
        tag_id = request.GET.getlist('tags')[0]
        if tag_id != '-1' :
            tag = Tag.objects.get(pk=tag_id)
            performances_jour = tag.performances.filter(date__gte=timezone.now()).order_by('date')
        

    for perf in performances_jour:
        artistes = Artiste.objects.filter(performance=perf)
        if perf.date not in performances_par_jour.keys():
            performances_par_jour[perf.date] = [(perf,artistes)]
        else :
            performances_par_jour[perf.date].append((perf,artistes))
    news_par_jours = dict()
    news_jour = News.objects.filter(date__gte=timezone.now()).order_by('date')
    for news in news_jour:
        if news.date not in news_par_jours.keys():
            news_par_jours[news.date] = [news]
        else :
            news_par_jours[news.date].append(news)
    return render(request, 'accueil.html', {'tag_form':tag_form,'tag_data': Tag.objects.filter(visible=True),'nom_festival':festival.nom,'performances_par_jour':performances_par_jour,'logo':festival.logo, 'news_par_jours':news_par_jours})

# CONFIGURATION
def configuration(request):
    """
    Renvoyer la création s'il n'y a pas de configuration d'enregistrée dans la base de données
    Renvoyer la page de détail sinon.
    """
    form = ConfigurationFestivalForm()
    partenaire_form = PartenaireForm()
    artiste_form = ArtisteForm()
    if request.method == "GET":
        configuration = ConfigurationFestival.objects.all()
        if configuration.exists():
            config_instance = configuration.first()
            partenaires = Partenaire.objects.filter(id__in=config_instance.partenaires.all()).all()
            return render(request,'configuration/configuration_detail.html',{'configuration':config_instance,'partenaires':partenaires})
        return render(request,'configuration/configuration_create.html',{'form':form,'partenaire_form':partenaire_form,"artiste_form":artiste_form,})
    elif request.method == "POST":
        form = ConfigurationFestivalForm(request.POST, request.FILES)
        if form.is_valid():
            Tag.objects.all().delete()
            generer_tags_date_festival(form.cleaned_data['date_debut'],form.cleaned_data['date_fin'])
            form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_config = timezone.now()
            modif.save()
            return redirect('API_festivals:configuration')
    return render(request,'configuration/configuration_create.html',{'form':form,'partenaire_form':partenaire_form,"artiste_form":artiste_form})

@configuration_required
def configuration_update(request):
    configuration = ConfigurationFestival.objects.all().first()
    chemin_logo = str(configuration.logo)
    configuration_form = ConfigurationFestivalForm(instance=configuration)
    if request.method == 'POST':
        configuration_form = ConfigurationFestivalForm(request.POST, request.FILES, instance=configuration)
        if configuration_form.has_changed() and configuration_form.is_valid():
            if "logo" in configuration_form.changed_data:
                try :
                    os.remove(chemin_logo)
                except FileNotFoundError :
                    pass
            configuration_form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_config = timezone.now()
            modif.save()
            return redirect('API_festivals:configuration')
    partenaire_form =PartenaireForm()
    artiste_form = ArtisteForm()
    return render(request, 'configuration/configuration_update.html', {'form': configuration_form, 'partenaire_form':partenaire_form, "artiste_form":artiste_form,'configuration': configuration})

@configuration_required
def configuration_delete(request):
    configuration = ConfigurationFestival.objects.all().first()
    try:
        os.remove(str(configuration.logo))
        os.remove(str(configuration.video_promo))
    except FileNotFoundError:
        pass
    if get_parameters("Delete_all_on_configuration_delete") == True:
        export_data()
        delete_all_data()
    configuration.delete()
    modif = Modification.objects.all().first()
    modif.date_modif_config = timezone.now()
    modif.save()
    return redirect("API_festivals:configuration")

# ARTISTES
@configuration_required
def artistes(request,page):
    artistes = Artiste.objects.all()
    logo = ConfigurationFestival.objects.all().first().logo
    form = SearchForm(request.GET)
    if form.is_valid():
        search_term = form.cleaned_data['search']
        artistes = artistes.filter(nom__icontains=search_term)
    render_left_arrow,render_right_arrow,artistes = pagination(artistes,page,Artiste.objects.all())
    return render(request, 'artistes/artistes.html',{"logo":logo,"artistes": artistes,"form":form,
     "render_right_arrow":render_right_arrow,"render_left_arrow":render_left_arrow, "page_precedente": page-1, "page_suivante": page+1})

@configuration_required
def artiste_create(request):
    modal = request.GET.get('modal',False)
    logo = ConfigurationFestival.objects.all().first().logo
    referer = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        artiste_form = ArtisteForm(request.POST, request.FILES)
        if artiste_form.is_valid():
            artiste_form.save()
            modif = Modification.objects.all().first()
            modif.date_modif_artiste = timezone.now()
            modif.save()
            if not modal : 
                return redirect('API_festivals:artistes', page=1)
            elif 'configuration' in referer:
                if 'update' in referer:
                    return redirect('API_festivals:configuration_update')
                elif 'create' in referer :
                    return redirect('API_festivals:configuration')
            else : 
                if 'update' in referer:
                    return redirect('API_festivals:performance_update')
                elif 'create' in referer :
                    return redirect('API_festivals:performance_create')
    else:
        artiste_form = ArtisteForm()
    return render(request, 'artistes/artiste_create.html', {'form': artiste_form,'logo':logo})

@configuration_required
def artiste_detail(request, id):
    perf_exist = False
    logo = ConfigurationFestival.objects.all().first().logo
    artiste = get_object_or_404(Artiste,id=id)
    perfs = Performance.objects.filter(artistes=artiste)
    if perfs.exists():
        perf_exist = True
    artistes = artiste.recommendations.all()
    template = "artistes/artiste_detail.html"
    context = {'artiste': artiste,'logo':logo,'artistes':artistes,'perf_exist':perf_exist}
    return render(request, template, context)

@configuration_required
def artiste_update(request, id):
    if Artiste.objects.all().exists():
        logo = ConfigurationFestival.objects.all().first().logo
        artiste = get_object_or_404(Artiste,id=id)
        chemin_image = str(artiste.image)
        artiste_form = ArtisteForm(instance=artiste)
        if request.method == 'POST':
            artiste_form = ArtisteForm(request.POST, request.FILES, instance=artiste)
            if artiste_form.has_changed() and artiste_form.is_valid():
                try : 
                    if "image" in artiste_form.changed_data:
                        os.remove(chemin_image)
                except FileNotFoundError :
                    pass
                finally :
                    artiste_form.save()
                    modif = Modification.objects.all().first()
                    modif.date_modif_artiste = timezone.now()
                    modif.save()
                    return redirect('API_festivals:artiste_detail', id=id)
        return render(request, 'artistes/artiste_update.html', {'logo':logo,'form': artiste_form, 'artiste': artiste})
    else :
        return redirect('API_festivals:artiste_create')

@configuration_required
def artiste_delete(request, id):
    artiste = get_object_or_404(Artiste,id=id)
    confirmation = request.GET.get('confirmation',False)
    perfs = Performance.objects.filter(artistes=artiste)
    if confirmation:
        for perf in perfs:
            perf.delete()
    try :
        os.remove(str(artiste.image.path)) 
    except FileNotFoundError:
        pass
    finally:
        artiste.delete()
    # Update modification date
    modif = Modification.objects.first()
    modif.date_modif_artiste = timezone.now()
    modif.save()
    return redirect("API_festivals:artistes", page=1)

# PARTENAIRES
@configuration_required

apps/Astrolabe/API_festivals/templates/accueil.html
{% extends 'base.html' %}
{% block title %}Accueil{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<script>
  function switchPage() {
    let bouton = document.getElementById("boutonSwitch");
    let corps = document.getElementById("corps");
    if (bouton.name === "news") {
      bouton.remove();
      let contenuCorps = corps.innerHTML;
      corps.innerHTML = "<button class=\"btn btn-primary\" id=\"boutonSwitch\" name=\"performances\" onclick=\"switchPage()\">Afficher les performances</button>" + contenuCorps;
      document.getElementById("performances").hidden = true;
      document.getElementById("news").hidden = false;
      document.getElementById("performances").classList.add("slide-out");
      document.getElementById("news").classList.remove("slide-out");
      document.getElementById("news").classList.add("slide-in");
    } else if (bouton.name === "performances") {
      bouton.remove();
      let contenuCorps = corps.innerHTML;
      corps.innerHTML = "<button class=\"btn btn-primary margeux-bottom\" id=\"boutonSwitch\" name=\"news\" onclick=\"switchPage()\">Afficher les news</button>" + contenuCorps;
      document.getElementById("performances").hidden = false;
      document.getElementById("news").hidden = true;
      document.getElementById("performances").classList.remove("slide-out");
      document.getElementById("performances").classList.add("slide-in");
      document.getElementById("news").classList.add("slide-out");
    }
  }
</script>

<div id="corps">
  <button class="btn btn-primary" id="boutonSwitch" name="news" onclick="switchPage()">Afficher les news</button>
  <div id="performances" class="">
          <div class="btn-group" role="group" style="margin-top: 1em;">
              <form id="tagForm" method="get" action="{% url 'API_festivals:accueil' %}">
                  {% csrf_token %}
                  <button type="submit" name="tags" value="-1" class="tag-button tous">Tous</button>
                  {% for tag in tag_data %}
                      <button type="submit" name="tags" value="{{ tag.pk }}" class="tag-button">{{ tag }}</button>
                  {% endfor %}
              </form>
          </div>
    <h2>Prochaines performances du {{ nom_festival }}</h2>
    {% for date, performances in performances_par_jour.items %}
    <h3>{{ date }}</h3>
    <div class="row">
      <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for performance, artistes in performances %}
    <div class="col">
        <a class="nolink" href="{% url 'API_festivals:performance_detail' performance.id %}">
            <div class="card entity" style="margin-bottom: 1rem;">
                <img class="card-img-top rounded" src="/{{artistes.0.image}}" alt="{{artistes.0.nom}}" style="object-fit: cover; width:100%; height: 150px;">
                <div class="card-body">
                    <h3 class="card-title" >{{ performance.nom }}</h3>
                    <div style="margin-top: 2em;">
                        <p class="card-text">Heure de début : {{performance.heure_debut}}</p>
                        <p class="card-text">Heure de fin : {{performance.heure_fin}}</p>
                        <p class="card-text">Scène : {{performance.scene.nom}}</p>
                    </div>
                </div>
                <div class="card-footer">
                    {% for artiste in artistes %}
                    <a class="card-link" href="{% url 'API_festivals:artiste_detail' artiste.id %}">{{artiste.nom}}</a>
                    {% endfor %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
    </div>
    </div>
    {% endfor %}
  </div>
</div>


  <div id="news" class="" hidden>
    <h2>Prochaines news du {{ nom_festival }}</h2>
    {% for date, news in news_par_jours.items %}
    <h3>{{date}}</h3>
    {% for nouvelle in news %}
    <div class="col-12 col-sm-6 col-md-4 col-lg-3">
      <a class="nolink" href="{% url 'API_festivals:news_detail' nouvelle.id %}">
        <div class="card entity" style="margin-bottom: 1rem;">
            <img class="card-img-top rounded" src="/{{nouvelle.image}}" alt="{{nouvelle.titre}}" style="object-fit: cover; width:100%; height: 150px;">
            <div class="card-body">
                <h3 class="card-title" >{{ nouvelle.date }}</h3>
                <p class="card-text">{{nouvelle.titre}}</p>
            </div>
        </div>
    </a>
    </div>
    {% endfor %}
    {% endfor %}
  </div>

  <style>
    @keyframes astroslide-out {
    0% {
        transform: translateX(0%);
    }
    100% {
        transform: translateX(50%);
    }
}

@keyframes astroslide-in {
    0% {
      transform: translateX(50%);
    }
    100% {
      transform: translateX(0%);
    }
}

div.slide-out {
    animation: astroslide-out 0.3s ease-in-out;
}

div.slide-in {
    animation: astroslide-in 0.3s ease-in-out;
}
    ul.errorlist {display:none;}

.margeux-bottom {
  margin-bottom: 2em;
}

  </style>
</div>
{% endblock %}

apps/Astrolabe/API_festivals/templates/parametres.html
{% extends 'base.html' %}
{% block title %}Accueil{% endblock %}
{% block logo %}
<img src="/{{logo}}" style="width:100%; height: 6vh;" class="rounded" alt="Festival">
{% endblock %}
{% block content %}
<h1>Paramètres</h1>
<div class="container-fluid mt-4 border">
    <h2>Import</h2>
<form method="post" enctype="multipart/form-data" action="{% url 'API_festivals:parametres'%}?changement=True">
    {% csrf_token %}
    <input type="file" style="margin-bottom:2em;" name="json_file">
    <input type="submit" style="margin-bottom:2em; max-width: 35%;" class="" value="Importer les données de la base de données"></input>
</form>
</div>
<div class="container-fluid mt-4 border">
    <h2>Export</h2>
    <a class="btn btn-primary" href="{% url 'API_festivals:parametres'%}?changement=True">Exporter les données</a>
</div>
<form id="forme" method="post" enctype="multipart/form-data" action="{% url 'API_festivals:parametres'%}">
    {% csrf_token %}
<div class="container-fluid mt-4 border">
    {{form.as_p}}
    <input type="submit" value="Enregistrer" form="forme">
</div>
</form>
<style>
</style>
{% endblock %}